;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Pickpacker.Station.Labeer",NewTagName="Pickpacker.Station.Labeler")
+GameplayTagRedirects=(OldTagName="Pickpacker.Parcel.Item.Food",NewTagName="Pickpacker.Parcel.Item.FoodMaterials")
+GameplayTagList=(Tag="Item",DevComment="")
+GameplayTagList=(Tag="Item.Credential.RepairDisk",DevComment="")
+GameplayTagList=(Tag="Item.Information",DevComment="")
+GameplayTagList=(Tag="Item.Key",DevComment="")
+GameplayTagList=(Tag="Item.Key.Bundle",DevComment="")
+GameplayTagList=(Tag="Item.Part.EVT03",DevComment="")
+GameplayTagList=(Tag="Item.Tool",DevComment="")
+GameplayTagList=(Tag="Item.Tool.Wrench",DevComment="")
+GameplayTagList=(Tag="Pickpacker",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Anchor",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Anchor.Exit",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Anchor.Parcel",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Anchor.Patrol",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Anchor.Spawn",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Anchor.Station",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel.Classification",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel.Classification.Contraband",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel.Classification.Fragile",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel.Classification.Standard",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel.Item",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel.Item.Chemicals",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel.Item.ConsumerGoods",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel.Item.Electronics",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel.Item.FoodMaterials",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel.Item.Industral",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel.Item.Luxury",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Parcel.Item.MedicalSupplies",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Station",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Station.Labeler",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Station.Scanner",DevComment="")
+GameplayTagList=(Tag="Pickpacker.Station.Sorter",DevComment="")
+GameplayTagList=(Tag="UseAction",DevComment="")
+GameplayTagList=(Tag="UseAction.Credential",DevComment="")
+GameplayTagList=(Tag="UseAction.Credential.RepairDisk",DevComment="")
+GameplayTagList=(Tag="UseAction.Key",DevComment="")
+GameplayTagList=(Tag="UseAction.Key.Open.MaintenanceDoor",DevComment="")
+GameplayTagList=(Tag="UseAction.Part",DevComment="")
+GameplayTagList=(Tag="UseAction.Part.Install.EVT03",DevComment="")
+GameplayTagList=(Tag="UseAction.Tool",DevComment="")
+GameplayTagList=(Tag="UseAction.Tool.PryOpen",DevComment="")
+GameplayTagList=(Tag="UseAction.Tool.Unscrew",DevComment="")
+GameplayTagList=(Tag="World",DevComment="")
+GameplayTagList=(Tag="World.Power",DevComment="")
+GameplayTagList=(Tag="World.Power.On",DevComment="")

